spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/svsp2?useUnicode=true&characterEncoding=utf8
    username: root
    password: root1234
mybatis:
  mapper-locations: classpath:mapper/*.xml