spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/svsp2?useUnicode=true&characterEncoding=utf8
    username: root
    password: c123456789
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB  # 单个文件最大限制
      max-request-size: 2000MB  # 多文件上传时，总的大小
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    #root: debug  # 将整个项目的日记级别都调整为debug，显示、记录所有的日志信息，包括debug、info
    edu.cxy.svspcxy: debug  # 指定某个包下的日志级别为debug，其它默认为info
alibaba:
  cloud:
    access-key: LTAI5tPpx7DhgVdMYsUnyp46   # 自己的key
    secret-key: G53GyuyapM0pQPG1DrBJdP1441feI1  # 自己的秘钥
    oss:
      endpoint: oss-cn-chengdu.aliyuncs.com  # oss存储地址
      bucketName: svsp-test  # 桶名
    region: cn-shanghai  # 接入区域
    endpoint: green-cip.cn-shanghai.aliyuncs.com  # 接入地址